gitlab:
  domain: "{example.com}"
  protocol: "https://"
  ssh_sub_domain: "services"
  tls_credential_name: "{your-tls-secret-name}"

  persistence:
    enabled: true
    volumeName: "data"
    accessMode: ReadWriteOnce
    size: 64Gi
    storageClass: "local-path"

  etcPersistence:
    volumeName: "gitlab-etc-claim"
    accessMode: ReadWriteOnce
    size: 100Mi
    storageClass: "local-path"

  shmVolume:
    enabled: true
    sizeLimit:

smtp:
  server: "smtp.gmail.com"
  user: "{mtp outmail user name}"
postgresql:
  host: "internal-postgresql.internal-postgresql.svc.cluster.local"
  port: "5432"
  username: "gitlab"
  database: "gitlabhq_production"

redis:
  host: "redis-master.gitlab.svc.cluster.local"
  port: "6379"