apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: {{ .Release.Namespace }}
data:
  gitlab.rb: |
    external_url 'http://gitlab.{{ .Values.gitlab.domain }}'
    gitlab_rails['initial_root_password'] = '{{ .Values.gitlab.initial_root_password }}'
    gitlab_rails['gitlab_shell_ssh_port'] = 2222
    postgresql['enable'] = false
    gitlab_rails['db_host'] = '{{ .Values.postgresql.host }}'
    gitlab_rails['db_port'] = '{{ .Values.postgresql.port }}'
    gitlab_rails['db_username'] = '{{ .Values.postgresql.username }}'
    gitlab_rails['db_password'] = '{{ .Values.postgresql.password }}'
    gitlab_rails['db_database'] = '{{ .Values.postgresql.database }}'
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'utf8'
    redis['enable'] = false
    gitlab_rails['redis_host'] = '{{ .Values.redis.host }}'
    gitlab_rails['redis_port'] = '{{ .Values.redis.port }}'
    # gitlab_rails['redis_connect_timeout'] = 5
    # gitlab_rails['redis_read_timeout'] =5
    # gitlab_rails['redis_write_timeout'] = 5

    # smtp
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = '{{ .Values.smtp.server }}'
    gitlab_rails['smtp_domain'] = '{{ .Values.smtp.server }}'
    gitlab_rails['smtp_port'] = 587
    gitlab_rails['smtp_user_name'] = '{{ .Values.smtp.user }}'
    gitlab_rails['smtp_password'] = '{{ .Values.smtp.password }}'
    gitlab_rails['smtp_authentication'] = 'login'
    gitlab_rails['smtp_enable_starttls_auto'] = true
    gitlab_rails['smtp_tls'] = false
    gitlab_rails['smtp_pool'] = false
    # nginx
    nginx['client_max_body_size'] = '256m'
