apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
type: Opaque
stringData:
  initial_root_password: <root_password>
  smtp_password: <smtp_password>
  postgresql_password: <postgresql_password>